#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
import subprocess

if __name__ == '__main__':
	if len(sys.argv) > 1:
		command = "nohup /bin/sh /mnt/tools/ide/clion-2016.1/bin/clion.sh " + sys.argv[1]
	else:
		command = "nohup /bin/sh /mnt/tools/ide/clion-2016.1/bin/clion.sh"
	p=subprocess.Popen(command, shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)  
	p.wait()