#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import sys
from threading import Timer


def suspend():
	sudoPassword = '2222'
	command = 'pm-suspend'
	p = os.system('echo %s|sudo -S %s' % (sudoPassword, command))
	# os.system('sudo pm-suspend')


if __name__ == '__main__':
	t = 60
	try:
		t = int(sys.argv[1])
	except Exception as e:
		print('Exception:', e)
	finally:
		timer = Timer(t, suspend)
		print('suspend after %rs' %t)
		timer.start()
