#! /usr/bin/env python3
#! coding: utf-8

import sys
import os

if __name__ == '__main__':
	if len(sys.argv) > 1:
		os.system('sh /mnt/tools/ide/pycharm-5.0.4/bin/pycharm.sh %r' % sys.argv[1])
	else:
		os.system('sh /mnt/tools/ide/pycharm-5.0.4/bin/pycharm.sh')
